-- liquibase formatted sql
-- changeset evgeny:8
insert into categories (category) values ("art and entertainment>books and literature>best-sellers");
insert into categories (category) values ("art and entertainment>books and literature>children's books");
insert into categories (category) values ("art and entertainment>books and literature>e-books");
insert into categories (category) values ("art and entertainment>books and literature>fan fiction");
insert into categories (category) values ("art and entertainment>books and literature>magazines");
insert into categories (category) values ("art and entertainment>books and literature>mythology");
insert into categories (category) values ("art and entertainment>books and literature>non-fiction");
insert into categories (category) values ("art and entertainment>books and literature>poetry");
insert into categories (category) values ("art and entertainment>books and literature>reference books");
insert into categories (category) values ("art and entertainment>books and literature>romance novels");
insert into categories (category) values ("art and entertainment>books and literature>science fiction");
insert into categories (category) values ("art and entertainment>books and literature>textbooks");
insert into categories (category) values ("art and entertainment>books and literature");
insert into categories (category) values ("art and entertainment>celebrity fan and gossip");
insert into categories (category) values ("art and entertainment>comics and animation>anime and manga");
insert into categories (category) values ("art and entertainment>comics and animation>cartoons");
insert into categories (category) values ("art and entertainment>comics and animation>comics");
insert into categories (category) values ("art and entertainment>dance>ballet");
insert into categories (category) values ("art and entertainment>dance>ballroom dance");
insert into categories (category) values ("art and entertainment>dance>belly dance");
insert into categories (category) values ("art and entertainment>dance>modern dance");
insert into categories (category) values ("art and entertainment>dance>pole dancing");
insert into categories (category) values ("art and entertainment>dance");
insert into categories (category) values ("art and entertainment>humor");
insert into categories (category) values ("art and entertainment>movies>film festivals and awards");
insert into categories (category) values ("art and entertainment>movies and tv>action");
insert into categories (category) values ("art and entertainment>movies and tv>animated");
insert into categories (category) values ("art and entertainment>movies and tv>bollywood");
insert into categories (category) values ("art and entertainment>movies and tv>children's");
insert into categories (category) values ("art and entertainment>movies and tv>classics>silent films>");
insert into categories (category) values ("art and entertainment>movies and tv>classics");
insert into categories (category) values ("art and entertainment>movies and tv>comedies");
insert into categories (category) values ("art and entertainment>movies and tv>cult classics");
insert into categories (category) values ("art and entertainment>movies and tv>documentaries");
insert into categories (category) values ("art and entertainment>movies and tv>dramas");
insert into categories (category) values ("art and entertainment>movies and tv>horror");
insert into categories (category) values ("art and entertainment>movies and tv>independent");
insert into categories (category) values ("art and entertainment>movies and tv>movies>reviews>");
insert into categories (category) values ("art and entertainment>movies and tv>movies>trailers>");
insert into categories (category) values ("art and entertainment>movies and tv>movies");
insert into categories (category) values ("art and entertainment>movies and tv>reality");
insert into categories (category) values ("art and entertainment>movies and tv>romantic comedies");
insert into categories (category) values ("art and entertainment>movies and tv>talk shows");
insert into categories (category) values ("art and entertainment>movies and tv>television");
insert into categories (category) values ("art and entertainment>movies and tv>thrillers");
insert into categories (category) values ("art and entertainment>movies and tv>westerns");
insert into categories (category) values ("art and entertainment>music>music genres>blues>");
insert into categories (category) values ("art and entertainment>music>music genres>classical music>");
insert into categories (category) values ("art and entertainment>music>music genres>country music>");
insert into categories (category) values ("art and entertainment>music>music genres>easy listening>");
insert into categories (category) values ("art and entertainment>music>music genres>electronic music>");
insert into categories (category) values ("art and entertainment>music>music genres>folk music>");
insert into categories (category) values ("art and entertainment>music>music genres>hip hop>");
insert into categories (category) values ("art and entertainment>music>music genres>jazz>");
insert into categories (category) values ("art and entertainment>music>music genres>opera>");
insert into categories (category) values ("art and entertainment>music>music genres>pop music>");
insert into categories (category) values ("art and entertainment>music>music genres>punk>");
insert into categories (category) values ("art and entertainment>music>music genres>religious music>");
insert into categories (category) values ("art and entertainment>music>music genres>rock music>");
insert into categories (category) values ("art and entertainment>music>music genres>ska>");
insert into categories (category) values ("art and entertainment>music>music genres>soul music>");
insert into categories (category) values ("art and entertainment>music>music genres>soundtracks>");
insert into categories (category) values ("art and entertainment>music>music genres>world music>");
insert into categories (category) values ("art and entertainment>music>music reference>music composition and theory>");
insert into categories (category) values ("art and entertainment>music>music reference>sheet music>");
insert into categories (category) values ("art and entertainment>music>musical instruments>drums>");
insert into categories (category) values ("art and entertainment>music>musical instruments>guitars>");
insert into categories (category) values ("art and entertainment>music>musical instruments>pianos>");
insert into categories (category) values ("art and entertainment>music>musical instruments");
insert into categories (category) values ("art and entertainment>music>recording industry>music awards>");
insert into categories (category) values ("art and entertainment>music>recording industry>record labels>");
insert into categories (category) values ("art and entertainment>music>recording industry");
insert into categories (category) values ("art and entertainment>music>singing");
insert into categories (category) values ("art and entertainment>music");
insert into categories (category) values ("art and entertainment>radio>podcasts");
insert into categories (category) values ("art and entertainment>radio>radio programs");
insert into categories (category) values ("art and entertainment>radio>talk radio");
insert into categories (category) values ("art and entertainment>radio");
insert into categories (category) values ("art and entertainment>shows and events>beauty contest");
insert into categories (category) values ("art and entertainment>shows and events>circus");
insert into categories (category) values ("art and entertainment>shows and events>classical concert");
insert into categories (category) values ("art and entertainment>shows and events>concert");
insert into categories (category) values ("art and entertainment>shows and events>conference");
insert into categories (category) values ("art and entertainment>shows and events>exhibition");
insert into categories (category) values ("art and entertainment>shows and events>fair");
insert into categories (category) values ("art and entertainment>shows and events>festival");
insert into categories (category) values ("art and entertainment>shows and events>sports event");
insert into categories (category) values ("art and entertainment>theatre>theatre awards");
insert into categories (category) values ("art and entertainment>theatre>theatre companies");
insert into categories (category) values ("art and entertainment>theatre");
insert into categories (category) values ("art and entertainment>visual art and design>architecture");
insert into categories (category) values ("art and entertainment>visual art and design>art and craft supplies");
insert into categories (category) values ("art and entertainment>visual art and design>art museums and galleries");
insert into categories (category) values ("art and entertainment>visual art and design>arts education");
insert into categories (category) values ("art and entertainment>visual art and design>design>graphic design>");
insert into categories (category) values ("art and entertainment>visual art and design>design>industrial and product design>");
insert into categories (category) values ("art and entertainment>visual art and design>design>interior design>");
insert into categories (category) values ("art and entertainment>visual art and design>design");
insert into categories (category) values ("art and entertainment>visual art and design>digital art");
insert into categories (category) values ("art and entertainment>visual art and design>drawing");
insert into categories (category) values ("art and entertainment>visual art and design>painting");
insert into categories (category) values ("art and entertainment>visual art and design>performance art");
insert into categories (category) values ("art and entertainment>visual art and design>restoration");
insert into categories (category) values ("art and entertainment>visual art and design>sculpture");
insert into categories (category) values ("art and entertainment>visual art and design");
insert into categories (category) values ("art and entertainment");
insert into categories (category) values ("automotive and vehicles>auto parts");
insert into categories (category) values ("automotive and vehicles>auto repair");
insert into categories (category) values ("automotive and vehicles>bicycles and accessories>mountain bikes");
insert into categories (category) values ("automotive and vehicles>bicycles and accessories");
insert into categories (category) values ("automotive and vehicles>boats and watercraft");
insert into categories (category) values ("automotive and vehicles>buying and selling cars");
insert into categories (category) values ("automotive and vehicles>campers and rvs");
insert into categories (category) values ("automotive and vehicles>cars>car culture");
insert into categories (category) values ("automotive and vehicles>cars>car industry");
insert into categories (category) values ("automotive and vehicles>cars>convertible");
insert into categories (category) values ("automotive and vehicles>cars>coupe");
insert into categories (category) values ("automotive and vehicles>cars>crossover");
insert into categories (category) values ("automotive and vehicles>cars>diesel");
insert into categories (category) values ("automotive and vehicles>cars>hatchback");
insert into categories (category) values ("automotive and vehicles>cars>hybrid");
insert into categories (category) values ("automotive and vehicles>cars>luxury");
insert into categories (category) values ("automotive and vehicles>cars>performance vehicles");
insert into categories (category) values ("automotive and vehicles>cars>sedan");
insert into categories (category) values ("automotive and vehicles>cars>vintage cars");
insert into categories (category) values ("automotive and vehicles>cars>wagon");
insert into categories (category) values ("automotive and vehicles>cars");
insert into categories (category) values ("automotive and vehicles>certified pre-owned");
insert into categories (category) values ("automotive and vehicles>commercial vehicles");
insert into categories (category) values ("automotive and vehicles>electric vehicles");
insert into categories (category) values ("automotive and vehicles>minivan");
insert into categories (category) values ("automotive and vehicles>motor shows");
insert into categories (category) values ("automotive and vehicles>motorcycles");
insert into categories (category) values ("automotive and vehicles>off-road vehicles");
insert into categories (category) values ("automotive and vehicles>road-side assistance");
insert into categories (category) values ("automotive and vehicles>scooters and mopeds");
insert into categories (category) values ("automotive and vehicles>trucks and suvs>pickup trucks");
insert into categories (category) values ("automotive and vehicles>trucks and suvs>suvs");
insert into categories (category) values ("automotive and vehicles>trucks and suvs>truck accessories");
insert into categories (category) values ("automotive and vehicles>vehicle brands>acura");
insert into categories (category) values ("automotive and vehicles>vehicle brands>alfa romeo");
insert into categories (category) values ("automotive and vehicles>vehicle brands>audi");
insert into categories (category) values ("automotive and vehicles>vehicle brands>bentley");
insert into categories (category) values ("automotive and vehicles>vehicle brands>buick");
insert into categories (category) values ("automotive and vehicles>vehicle brands>cadillac");
insert into categories (category) values ("automotive and vehicles>vehicle brands>chevrolet");
insert into categories (category) values ("automotive and vehicles>vehicle brands>chrysler");
insert into categories (category) values ("automotive and vehicles>vehicle brands>ferrari");
insert into categories (category) values ("automotive and vehicles>vehicle brands>fiat");
insert into categories (category) values ("automotive and vehicles>vehicle brands>ford");
insert into categories (category) values ("automotive and vehicles>vehicle brands>honda");
insert into categories (category) values ("automotive and vehicles>vehicle brands>hyundai");
insert into categories (category) values ("automotive and vehicles>vehicle brands>isuzu");
insert into categories (category) values ("automotive and vehicles>vehicle brands>jeep");
insert into categories (category) values ("automotive and vehicles>vehicle brands>kia");
insert into categories (category) values ("automotive and vehicles>vehicle brands>lamborghini");
insert into categories (category) values ("automotive and vehicles>vehicle brands>land rover");
insert into categories (category) values ("automotive and vehicles>vehicle brands>maserati");
insert into categories (category) values ("automotive and vehicles>vehicle brands>mazda");
insert into categories (category) values ("automotive and vehicles>vehicle brands>mercedes-benz");
insert into categories (category) values ("automotive and vehicles>vehicle brands>mitsubishi");
insert into categories (category) values ("automotive and vehicles>vehicle brands>nissan>infiniti>");
insert into categories (category) values ("automotive and vehicles>vehicle brands>nissan");
insert into categories (category) values ("automotive and vehicles>vehicle brands>peugeot");
insert into categories (category) values ("automotive and vehicles>vehicle brands>pontiac");
insert into categories (category) values ("automotive and vehicles>vehicle brands>porsche");
insert into categories (category) values ("automotive and vehicles>vehicle brands>rolls-royce");
insert into categories (category) values ("automotive and vehicles>vehicle brands>saab");
insert into categories (category) values ("automotive and vehicles>vehicle brands>scion");
insert into categories (category) values ("automotive and vehicles>vehicle brands>subaru");
insert into categories (category) values ("automotive and vehicles>vehicle brands>suzuki");
insert into categories (category) values ("automotive and vehicles>vehicle brands>toyota");
insert into categories (category) values ("automotive and vehicles>vehicle brands>volkswagen");
insert into categories (category) values ("automotive and vehicles>vehicle brands>volvo");
insert into categories (category) values ("automotive and vehicles>vehicle rental");
insert into categories (category) values ("automotive and vehicles");
insert into categories (category) values ("business and industrial>advertising and marketing>advertising");
insert into categories (category) values ("business and industrial>advertising and marketing>brand management");
insert into categories (category) values ("business and industrial>advertising and marketing>marketing");
insert into categories (category) values ("business and industrial>advertising and marketing>public relations");
insert into categories (category) values ("business and industrial>advertising and marketing>telemarketing");
insert into categories (category) values ("business and industrial>aerospace and defense>defense industry");
insert into categories (category) values ("business and industrial>aerospace and defense>space technology");
insert into categories (category) values ("business and industrial>aerospace and defense");
insert into categories (category) values ("business and industrial>agriculture and forestry>agriculture");
insert into categories (category) values ("business and industrial>agriculture and forestry>aquaculture");
insert into categories (category) values ("business and industrial>agriculture and forestry>crops and seed");
insert into categories (category) values ("business and industrial>agriculture and forestry>farms and ranches");
insert into categories (category) values ("business and industrial>agriculture and forestry>food production");
insert into categories (category) values ("business and industrial>agriculture and forestry>forestry");
insert into categories (category) values ("business and industrial>agriculture and forestry>horticulture");
insert into categories (category) values ("business and industrial>agriculture and forestry>livestock");
insert into categories (category) values ("business and industrial>agriculture and forestry>organic farming");
insert into categories (category) values ("business and industrial>automation>robotics");
insert into categories (category) values ("business and industrial>biomedical");
insert into categories (category) values ("business and industrial>business news");
insert into categories (category) values ("business and industrial>business operations>business plans");
insert into categories (category) values ("business and industrial>business operations>human resources>compensation and benefits>");
insert into categories (category) values ("business and industrial>business operations>human resources>payroll services>");
insert into categories (category) values ("business and industrial>business operations>human resources");
insert into categories (category) values ("business and industrial>business operations>management>business process>");
insert into categories (category) values ("business and industrial>business operations>management>project management>");
insert into categories (category) values ("business and industrial>business operations>management>supply chain management>");
insert into categories (category) values ("business and industrial>business operations");
insert into categories (category) values ("business and industrial>business software");
insert into categories (category) values ("business and industrial>chemicals industry>adhesives");
insert into categories (category) values ("business and industrial>chemicals industry>cleaning agents");
insert into categories (category) values ("business and industrial>chemicals industry>dyes and pigments");
insert into categories (category) values ("business and industrial>chemicals industry>plastics and polymers");
insert into categories (category) values ("business and industrial>chemicals industry");
insert into categories (category) values ("business and industrial>company>annual report");
insert into categories (category) values ("business and industrial>company>bankruptcy");
insert into categories (category) values ("business and industrial>company>earnings");
insert into categories (category) values ("business and industrial>company>joint venture");
insert into categories (category) values ("business and industrial>company>merger and acquisition");
insert into categories (category) values ("business and industrial>construction");
insert into categories (category) values ("business and industrial>energy>coal");
insert into categories (category) values ("business and industrial>energy>electricity");
insert into categories (category) values ("business and industrial>energy>natural gas");
insert into categories (category) values ("business and industrial>energy>nuclear power>nuclear accident>");
insert into categories (category) values ("business and industrial>energy>nuclear power");
insert into categories (category) values ("business and industrial>energy>oil>diesel fuel>");
insert into categories (category) values ("business and industrial>energy>oil>oil and gas prices>");
insert into categories (category) values ("business and industrial>energy>oil>oil company>");
insert into categories (category) values ("business and industrial>energy>oil");
insert into categories (category) values ("business and industrial>energy>renewable energy>biofuel>");
insert into categories (category) values ("business and industrial>energy>renewable energy>fuel cell>");
insert into categories (category) values ("business and industrial>energy>renewable energy>geothermal energy>");
insert into categories (category) values ("business and industrial>energy>renewable energy>hydroelectric energy>");
insert into categories (category) values ("business and industrial>energy>renewable energy>solar energy>");
insert into categories (category) values ("business and industrial>energy>renewable energy>wind energy>");
insert into categories (category) values ("business and industrial>energy>renewable energy");
insert into categories (category) values ("business and industrial>fashion industry");
insert into categories (category) values ("business and industrial>food industry");
insert into categories (category) values ("business and industrial>green solutions");
insert into categories (category) values ("business and industrial>hospitality industry>event planning");
insert into categories (category) values ("business and industrial>hospitality industry>food service");
insert into categories (category) values ("business and industrial>hospitality industry");
insert into categories (category) values ("business and industrial>iron and steel industry");
insert into categories (category) values ("business and industrial>logistics>air freight");
insert into categories (category) values ("business and industrial>logistics>freight train");
insert into categories (category) values ("business and industrial>logistics");
insert into categories (category) values ("business and industrial>manufacturing");
insert into categories (category) values ("business and industrial>metals");
insert into categories (category) values ("business and industrial>mining industry");
insert into categories (category) values ("business and industrial>paper industry");
insert into categories (category) values ("business and industrial>pharmaceutical industry");
insert into categories (category) values ("business and industrial>publishing");
insert into categories (category) values ("business and industrial>record company");
insert into categories (category) values ("business and industrial>shipbuilding");
insert into categories (category) values ("business and industrial>tanning");
insert into categories (category) values ("business and industrial>textile industry");
insert into categories (category) values ("business and industrial>war industry>weaponry");
insert into categories (category) values ("business and industrial");
insert into categories (category) values ("careers>career advice");
insert into categories (category) values ("careers>career planning");
insert into categories (category) values ("careers>job fairs");
insert into categories (category) values ("careers>job search");
insert into categories (category) values ("careers>nursing");
insert into categories (category) values ("careers>resume writing and advice");
insert into categories (category) values ("careers>telecommuting");
insert into categories (category) values ("careers>u.s. military");
insert into categories (category) values ("careers");
insert into categories (category) values ("education>adult education");
insert into categories (category) values ("education>alumni and reunions");
insert into categories (category) values ("education>art history");
insert into categories (category) values ("education>distance learning");
insert into categories (category) values ("education>english as a second language");
insert into categories (category) values ("education>grade school");
insert into categories (category) values ("education>graduate school>college");
insert into categories (category) values ("education>graduate school>college administration");
insert into categories (category) values ("education>graduate school>college life");
insert into categories (category) values ("education>graduate school");
insert into categories (category) values ("education>high school");
insert into categories (category) values ("education>homeschooling");
insert into categories (category) values ("education>homework and study tips");
insert into categories (category) values ("education>language learning");
insert into categories (category) values ("education>school>private school");
insert into categories (category) values ("education>school");
insert into categories (category) values ("education>special education");
insert into categories (category) values ("education>studying business");
insert into categories (category) values ("education>teaching and classroom resources>lesson plans");
insert into categories (category) values ("education>teaching and classroom resources>school supplies");
insert into categories (category) values ("education");
insert into categories (category) values ("family and parenting>adoption");
insert into categories (category) values ("family and parenting>babies and toddlers>baby clothes");
insert into categories (category) values ("family and parenting>babies and toddlers>baby food");
insert into categories (category) values ("family and parenting>babies and toddlers");
insert into categories (category) values ("family and parenting>children>daycare and preschool");
insert into categories (category) values ("family and parenting>children");
insert into categories (category) values ("family and parenting>eldercare");
insert into categories (category) values ("family and parenting>motherhood>artificial insemination");
insert into categories (category) values ("family and parenting>motherhood>pregnancy");
insert into categories (category) values ("family and parenting>motherhood");
insert into categories (category) values ("family and parenting>parenting teens");
insert into categories (category) values ("family and parenting>special needs kids");
insert into categories (category) values ("family and parenting");
insert into categories (category) values ("finance>accounting and auditing>billing and invoicing");
insert into categories (category) values ("finance>accounting and auditing>bookkeeping");
insert into categories (category) values ("finance>accounting and auditing>tax preparation and planning");
insert into categories (category) values ("finance>accounting and auditing");
insert into categories (category) values ("finance>bank>atms");
insert into categories (category) values ("finance>bank>bank account");
insert into categories (category) values ("finance>bank>checks");
insert into categories (category) values ("finance>bank");
insert into categories (category) values ("finance>financial news");
insert into categories (category) values ("finance>grants, scholarships and financial aid>financial aid");
insert into categories (category) values ("finance>grants, scholarships and financial aid>government grants");
insert into categories (category) values ("finance>grants, scholarships and financial aid>scholarships");
insert into categories (category) values ("finance>investing>beginning investing");
insert into categories (category) values ("finance>investing>brokerages");
insert into categories (category) values ("finance>investing>day trading");
insert into categories (category) values ("finance>investing>funds>exchange traded funds>");
insert into categories (category) values ("finance>investing>funds>hedge fund>");
insert into categories (category) values ("finance>investing>funds>mutual funds>");
insert into categories (category) values ("finance>investing>futures trading");
insert into categories (category) values ("finance>investing>options");
insert into categories (category) values ("finance>investing>portfolio");
insert into categories (category) values ("finance>investing>stocks");
insert into categories (category) values ("finance>investing>venture capital");
insert into categories (category) values ("finance>investing");
insert into categories (category) values ("finance>personal finance>debt management");
insert into categories (category) values ("finance>personal finance>financial planning>asset and portfolio management>");
insert into categories (category) values ("finance>personal finance>financial planning>estate planning>");
insert into categories (category) values ("finance>personal finance>financial planning>retirement and pension>");
insert into categories (category) values ("finance>personal finance>financial planning");
insert into categories (category) values ("finance>personal finance>insurance>car insurance>");
insert into categories (category) values ("finance>personal finance>insurance>health insurance>");
insert into categories (category) values ("finance>personal finance>insurance>homeowners insurance>");
insert into categories (category) values ("finance>personal finance>insurance>life insurance>");
insert into categories (category) values ("finance>personal finance>insurance>travel insurance>");
insert into categories (category) values ("finance>personal finance>insurance>vehicle insurance>");
insert into categories (category) values ("finance>personal finance>insurance");
insert into categories (category) values ("finance>personal finance>lending>credit cards>");
insert into categories (category) values ("finance>personal finance>lending>home financing>");
insert into categories (category) values ("finance>personal finance>lending>personal loans>");
insert into categories (category) values ("finance>personal finance>lending>student loans>");
insert into categories (category) values ("finance>personal finance>lending>vehicle financing>");
insert into categories (category) values ("finance>personal finance>saving");
insert into categories (category) values ("finance");
insert into categories (category) values ("food and drink>barbecues and grilling");
insert into categories (category) values ("food and drink>beverages>alcoholic beverages>cocktails and beer>");
insert into categories (category) values ("food and drink>beverages>alcoholic beverages>wine>");
insert into categories (category) values ("food and drink>beverages>non alcoholic beverages>bottled water>");
insert into categories (category) values ("food and drink>beverages>non alcoholic beverages>coffee and tea>");
insert into categories (category) values ("food and drink>beverages>non alcoholic beverages>soft drinks>");
insert into categories (category) values ("food and drink>beverages");
insert into categories (category) values ("food and drink>cuisines>american cuisine");
insert into categories (category) values ("food and drink>cuisines>chinese cuisine");
insert into categories (category) values ("food and drink>cuisines>french cuisine");
insert into categories (category) values ("food and drink>cuisines>indian cuisine");
insert into categories (category) values ("food and drink>cuisines>italian cuisine");
insert into categories (category) values ("food and drink>cuisines>japanese cuisine");
insert into categories (category) values ("food and drink>cuisines>mexican cuisine");
insert into categories (category) values ("food and drink>cuisines>regional cuisine");
insert into categories (category) values ("food and drink>desserts and baking");
insert into categories (category) values ("food and drink>dining out");
insert into categories (category) values ("food and drink>food>baked goods");
insert into categories (category) values ("food and drink>food>breakfast foods");
insert into categories (category) values ("food and drink>food>candy and sweets");
insert into categories (category) values ("food and drink>food>condiments and dressings");
insert into categories (category) values ("food and drink>food>fast food");
insert into categories (category) values ("food and drink>food>frozen food");
insert into categories (category) values ("food and drink>food>fruits and vegetables");
insert into categories (category) values ("food and drink>food>grains and pasta");
insert into categories (category) values ("food and drink>food>herbs and spices");
insert into categories (category) values ("food and drink>food>salads");
insert into categories (category) values ("food and drink>food>snack foods");
insert into categories (category) values ("food and drink>food allergies");
insert into categories (category) values ("food and drink>food and grocery retailers>bakeries");
insert into categories (category) values ("food and drink>food and grocery retailers>butchers");
insert into categories (category) values ("food and drink>food and grocery retailers>convenience stores");
insert into categories (category) values ("food and drink>food and grocery retailers>grocery stores");
insert into categories (category) values ("food and drink>gastronomy>slow food");
insert into categories (category) values ("food and drink>gastronomy");
insert into categories (category) values ("food and drink>health and lowfat cooking");
insert into categories (category) values ("food and drink>healthy eating");
insert into categories (category) values ("food and drink>kosher food");
insert into categories (category) values ("food and drink>vegan");
insert into categories (category) values ("food and drink>vegetarian");
insert into categories (category) values ("food and drink");
insert into categories (category) values ("health and fitness>addiction>alcoholism");
insert into categories (category) values ("health and fitness>addiction>smoking addiction");
insert into categories (category) values ("health and fitness>addiction>substance abuse");
insert into categories (category) values ("health and fitness>addiction");
insert into categories (category) values ("health and fitness>aging");
insert into categories (category) values ("health and fitness>alternative medicine>herbs for health");
insert into categories (category) values ("health and fitness>alternative medicine>holistic healing");
insert into categories (category) values ("health and fitness>alternative medicine>homeopathy");
insert into categories (category) values ("health and fitness>alternative medicine");
insert into categories (category) values ("health and fitness>dental care");
insert into categories (category) values ("health and fitness>disease>aids and hiv");
insert into categories (category) values ("health and fitness>disease>allergies");
insert into categories (category) values ("health and fitness>disease>arthritis");
insert into categories (category) values ("health and fitness>disease>asthma");
insert into categories (category) values ("health and fitness>disease>autism and pdd");
insert into categories (category) values ("health and fitness>disease>cancer>brain tumor>");
insert into categories (category) values ("health and fitness>disease>cancer");
insert into categories (category) values ("health and fitness>disease>cholesterol");
insert into categories (category) values ("health and fitness>disease>chronic fatigue syndrome");
insert into categories (category) values ("health and fitness>disease>chronic pain");
insert into categories (category) values ("health and fitness>disease>cold and flu");
insert into categories (category) values ("health and fitness>disease>deafness");
insert into categories (category) values ("health and fitness>disease>diabetes");
insert into categories (category) values ("health and fitness>disease>epidemic");
insert into categories (category) values ("health and fitness>disease>epilepsy");
insert into categories (category) values ("health and fitness>disease>gerd and acid reflux");
insert into categories (category) values ("health and fitness>disease>headaches and migraines");
insert into categories (category) values ("health and fitness>disease>heart disease");
insert into categories (category) values ("health and fitness>disease>ibs and crohn's disease");
insert into categories (category) values ("health and fitness>disease>incontinence");
insert into categories (category) values ("health and fitness>disease>infertility");
insert into categories (category) values ("health and fitness>disease>thyroid disease");
insert into categories (category) values ("health and fitness>disease");
insert into categories (category) values ("health and fitness>disorders>mental disorder>a.d.d.>");
insert into categories (category) values ("health and fitness>disorders>mental disorder>bipolar disorder>");
insert into categories (category) values ("health and fitness>disorders>mental disorder>depression>");
insert into categories (category) values ("health and fitness>disorders>mental disorder>panic and anxiety>");
insert into categories (category) values ("health and fitness>disorders>mental disorder");
insert into categories (category) values ("health and fitness>disorders>sleep disorders");
insert into categories (category) values ("health and fitness>disorders");
insert into categories (category) values ("health and fitness>drugs");
insert into categories (category) values ("health and fitness>exercise");
insert into categories (category) values ("health and fitness>incest and abuse support");
insert into categories (category) values ("health and fitness>men's health");
insert into categories (category) values ("health and fitness>nutrition");
insert into categories (category) values ("health and fitness>sexuality");
insert into categories (category) values ("health and fitness>sports medicine");
insert into categories (category) values ("health and fitness>therapy>physical therapy");
insert into categories (category) values ("health and fitness>therapy");
insert into categories (category) values ("health and fitness>weight loss");
insert into categories (category) values ("health and fitness>women's health");
insert into categories (category) values ("health and fitness");
insert into categories (category) values ("hobbies and interests>art and technology");
insert into categories (category) values ("hobbies and interests>arts and crafts>beadwork");
insert into categories (category) values ("hobbies and interests>arts and crafts>candle and soap making");
insert into categories (category) values ("hobbies and interests>arts and crafts>crochet");
insert into categories (category) values ("hobbies and interests>arts and crafts>jewelry making");
insert into categories (category) values ("hobbies and interests>arts and crafts>knitting");
insert into categories (category) values ("hobbies and interests>arts and crafts>photography");
insert into categories (category) values ("hobbies and interests>arts and crafts>pottery");
insert into categories (category) values ("hobbies and interests>arts and crafts>watchmaking");
insert into categories (category) values ("hobbies and interests>arts and crafts>woodworking");
insert into categories (category) values ("hobbies and interests>arts and crafts");
insert into categories (category) values ("hobbies and interests>astrology");
insert into categories (category) values ("hobbies and interests>birdwatching");
insert into categories (category) values ("hobbies and interests>cigars");
insert into categories (category) values ("hobbies and interests>collecting>stamps and coins");
insert into categories (category) values ("hobbies and interests>collecting");
insert into categories (category) values ("hobbies and interests>games>board games and puzzles");
insert into categories (category) values ("hobbies and interests>games>card games");
insert into categories (category) values ("hobbies and interests>games>chess");
insert into categories (category) values ("hobbies and interests>games>gambling");
insert into categories (category) values ("hobbies and interests>games>lottery");
insert into categories (category) values ("hobbies and interests>games>role playing games");
insert into categories (category) values ("hobbies and interests>games>video and computer games");
insert into categories (category) values ("hobbies and interests>getting published>freelance writing");
insert into categories (category) values ("hobbies and interests>getting published>screenwriting");
insert into categories (category) values ("hobbies and interests>getting published");
insert into categories (category) values ("hobbies and interests>guitar");
insert into categories (category) values ("hobbies and interests>home recording");
insert into categories (category) values ("hobbies and interests>inventors and patents");
insert into categories (category) values ("hobbies and interests>magic and illusion");
insert into categories (category) values ("hobbies and interests>needlework");
insert into categories (category) values ("hobbies and interests>paranormal phenomena>occult");
insert into categories (category) values ("hobbies and interests>paranormal phenomena>parapsychology");
insert into categories (category) values ("hobbies and interests>paranormal phenomena");
insert into categories (category) values ("hobbies and interests>reading");
insert into categories (category) values ("hobbies and interests>scrapbooking");
insert into categories (category) values ("hobbies and interests");
insert into categories (category) values ("home and garden>appliances>dishwashers");
insert into categories (category) values ("home and garden>appliances>microwaves");
insert into categories (category) values ("home and garden>appliances>refrigerators and freezers");
insert into categories (category) values ("home and garden>appliances>small appliances>blenders>");
insert into categories (category) values ("home and garden>appliances>small appliances>coffee maker>");
insert into categories (category) values ("home and garden>appliances>small appliances>food processors>");
insert into categories (category) values ("home and garden>appliances>small appliances>toasters and toaster ovens>");
insert into categories (category) values ("home and garden>appliances>stoves");
insert into categories (category) values ("home and garden>appliances");
insert into categories (category) values ("home and garden>bed and bath>bathroom");
insert into categories (category) values ("home and garden>bed and bath>bedroom>bedding and bed linens>");
insert into categories (category) values ("home and garden>bed and bath>bedroom>beds and headboards>");
insert into categories (category) values ("home and garden>bed and bath>bedroom>mattresses>");
insert into categories (category) values ("home and garden>bed and bath>bedroom");
insert into categories (category) values ("home and garden>environmental safety");
insert into categories (category) values ("home and garden>gardening and landscaping>gardening");
insert into categories (category) values ("home and garden>gardening and landscaping>landscaping");
insert into categories (category) values ("home and garden>gardening and landscaping>yard and patio");
insert into categories (category) values ("home and garden>home furnishings>lamps and lighting");
insert into categories (category) values ("home and garden>home furnishings>rugs and carpets");
insert into categories (category) values ("home and garden>home furnishings>sofas and chairs");
insert into categories (category) values ("home and garden>home furnishings");
insert into categories (category) values ("home and garden>home improvement and repair>house painting and finishing");
insert into categories (category) values ("home and garden>home improvement and repair>locks and locksmiths");
insert into categories (category) values ("home and garden>home improvement and repair>plumbing");
insert into categories (category) values ("home and garden>home improvement and repair>power tools");
insert into categories (category) values ("home and garden>home improvement and repair>roofing");
insert into categories (category) values ("home and garden>home improvement and repair");
insert into categories (category) values ("home and garden>interior decorating");
insert into categories (category) values ("home and garden>laundry");
insert into categories (category) values ("home and garden>luxury homes");
insert into categories (category) values ("home and garden>nursery and playroom");
insert into categories (category) values ("home and garden>pest control");
insert into categories (category) values ("home and garden>remodeling and construction");
insert into categories (category) values ("home and garden");
insert into categories (category) values ("law, govt and politics>armed forces>air force");
insert into categories (category) values ("law, govt and politics>armed forces>army");
insert into categories (category) values ("law, govt and politics>armed forces>marines");
insert into categories (category) values ("law, govt and politics>armed forces>navy");
insert into categories (category) values ("law, govt and politics>armed forces>veterans");
insert into categories (category) values ("law, govt and politics>commentary");
insert into categories (category) values ("law, govt and politics>espionage and intelligence>secret service");
insert into categories (category) values ("law, govt and politics>espionage and intelligence>surveillance");
insert into categories (category) values ("law, govt and politics>espionage and intelligence>terrorism");
insert into categories (category) values ("law, govt and politics>espionage and intelligence");
insert into categories (category) values ("law, govt and politics>government>courts and judiciary");
insert into categories (category) values ("law, govt and politics>government>embassies and consulates");
insert into categories (category) values ("law, govt and politics>government>executive branch");
insert into categories (category) values ("law, govt and politics>government>government agencies");
insert into categories (category) values ("law, govt and politics>government>government contracting and procurement");
insert into categories (category) values ("law, govt and politics>government>heads of state");
insert into categories (category) values ("law, govt and politics>government>legislative");
insert into categories (category) values ("law, govt and politics>government>parliament");
insert into categories (category) values ("law, govt and politics>government>state and local government");
insert into categories (category) values ("law, govt and politics>government");
insert into categories (category) values ("law, govt and politics>immigration");
insert into categories (category) values ("law, govt and politics>law enforcement>coast guard");
insert into categories (category) values ("law, govt and politics>law enforcement>fire department");
insert into categories (category) values ("law, govt and politics>law enforcement>highway patrol");
insert into categories (category) values ("law, govt and politics>law enforcement>police");
insert into categories (category) values ("law, govt and politics>law enforcement");
insert into categories (category) values ("law, govt and politics>legal issues>civil law>copyright>");
insert into categories (category) values ("law, govt and politics>legal issues>civil law");
insert into categories (category) values ("law, govt and politics>legal issues>civil rights");
insert into categories (category) values ("law, govt and politics>legal issues>civil rights>privacy>");
insert into categories (category) values ("law, govt and politics>legal issues>criminal law");
insert into categories (category) values ("law, govt and politics>legal issues>death penalty");
insert into categories (category) values ("law, govt and politics>legal issues>human rights");
insert into categories (category) values ("law, govt and politics>legal issues>international law");
insert into categories (category) values ("law, govt and politics>legal issues>legislation>building laws>");
insert into categories (category) values ("law, govt and politics>legal issues>legislation>education laws>");
insert into categories (category) values ("law, govt and politics>legal issues>legislation>family laws>");
insert into categories (category) values ("law, govt and politics>legal issues>legislation>health care laws>");
insert into categories (category) values ("law, govt and politics>legal issues>legislation>immigration laws>");
insert into categories (category) values ("law, govt and politics>legal issues>legislation>tax laws>");
insert into categories (category) values ("law, govt and politics>legal issues>legislation");
insert into categories (category) values ("law, govt and politics>legal issues");
insert into categories (category) values ("law, govt and politics>politics>domestic policy");
insert into categories (category) values ("law, govt and politics>politics>elections>local elections>");
insert into categories (category) values ("law, govt and politics>politics>elections>presidential elections>");
insert into categories (category) values ("law, govt and politics>politics>elections>referendums>");
insert into categories (category) values ("law, govt and politics>politics>elections");
insert into categories (category) values ("law, govt and politics>politics>foreign policy");
insert into categories (category) values ("law, govt and politics>politics>lobbying");
insert into categories (category) values ("law, govt and politics>politics>political parties");
insert into categories (category) values ("law, govt and politics>politics");
insert into categories (category) values ("law, govt and politics");
insert into categories (category) values ("news>international news");
insert into categories (category) values ("news>local news");
insert into categories (category) values ("news>national news");
insert into categories (category) values ("news");
insert into categories (category) values ("pets>animal welfare");
insert into categories (category) values ("pets>aquariums");
insert into categories (category) values ("pets>birds");
insert into categories (category) values ("pets>cats");
insert into categories (category) values ("pets>dogs");
insert into categories (category) values ("pets>large animals");
insert into categories (category) values ("pets>reptiles");
insert into categories (category) values ("pets>zoo");
insert into categories (category) values ("pets");
insert into categories (category) values ("real estate>apartments");
insert into categories (category) values ("real estate>architects");
insert into categories (category) values ("real estate>buying and selling homes");
insert into categories (category) values ("real estate>low income housing");
insert into categories (category) values ("real estate");
insert into categories (category) values ("religion and spirituality>alternative religions>pagan and wiccan");
insert into categories (category) values ("religion and spirituality>atheism and agnosticism");
insert into categories (category) values ("religion and spirituality>buddhism");
insert into categories (category) values ("religion and spirituality>christianity>catholicism");
insert into categories (category) values ("religion and spirituality>christianity>latter-day saints");
insert into categories (category) values ("religion and spirituality>christianity>orthodoxy");
insert into categories (category) values ("religion and spirituality>christianity>protestantism");
insert into categories (category) values ("religion and spirituality>christianity");
insert into categories (category) values ("religion and spirituality>hinduism");
insert into categories (category) values ("religion and spirituality>islam>islamic fundamentalism");
insert into categories (category) values ("religion and spirituality>islam");
insert into categories (category) values ("religion and spirituality>judaism");
insert into categories (category) values ("religion and spirituality");
insert into categories (category) values ("science>biology>biotechnology");
insert into categories (category) values ("science>biology>botany");
insert into categories (category) values ("science>biology>breeding");
insert into categories (category) values ("science>biology>cytology");
insert into categories (category) values ("science>biology>marine biology");
insert into categories (category) values ("science>biology>molecular biology");
insert into categories (category) values ("science>biology>zoology>endangered species>");
insert into categories (category) values ("science>biology>zoology>entomology>");
insert into categories (category) values ("science>biology>zoology>ornithology>");
insert into categories (category) values ("science>biology>zoology");
insert into categories (category) values ("science>biology");
insert into categories (category) values ("science>chemistry>organic chemistry");
insert into categories (category) values ("science>chemistry");
insert into categories (category) values ("science>computer science>artificial intelligence");
insert into categories (category) values ("science>computer science>cryptography");
insert into categories (category) values ("science>computer science>distributed systems");
insert into categories (category) values ("science>computer science>information science");
insert into categories (category) values ("science>computer science>software engineering");
insert into categories (category) values ("science>computer science");
insert into categories (category) values ("science>ecology>environmental disaster");
insert into categories (category) values ("science>ecology>pollution");
insert into categories (category) values ("science>ecology>waste management>recycling>");
insert into categories (category) values ("science>ecology>waste management>waste disposal>");
insert into categories (category) values ("science>ecology");
insert into categories (category) values ("science>engineering");
insert into categories (category) values ("science>geography>cartography");
insert into categories (category) values ("science>geography>topography");
insert into categories (category) values ("science>geography");
insert into categories (category) values ("science>geology>mineralogy");
insert into categories (category) values ("science>geology>seismology>earthquakes>");
insert into categories (category) values ("science>geology>volcanology>volcanic eruptions>");
insert into categories (category) values ("science>geology");
insert into categories (category) values ("science>mathematics>algebra");
insert into categories (category) values ("science>mathematics>arithmetic");
insert into categories (category) values ("science>mathematics>geometry");
insert into categories (category) values ("science>mathematics>statistics");
insert into categories (category) values ("science>mathematics");
insert into categories (category) values ("science>medicine>cardiology");
insert into categories (category) values ("science>medicine>dermatology");
insert into categories (category) values ("science>medicine>embryology");
insert into categories (category) values ("science>medicine>genetics");
insert into categories (category) values ("science>medicine>immunology");
insert into categories (category) values ("science>medicine>medical research");
insert into categories (category) values ("science>medicine>oncology");
insert into categories (category) values ("science>medicine>orthopedics");
insert into categories (category) values ("science>medicine>pediatrics");
insert into categories (category) values ("science>medicine>pharmacology");
insert into categories (category) values ("science>medicine>physiology");
insert into categories (category) values ("science>medicine>psychology and psychiatry>psychoanalysis>");
insert into categories (category) values ("science>medicine>psychology and psychiatry");
insert into categories (category) values ("science>medicine>surgery>cosmetic surgery>");
insert into categories (category) values ("science>medicine>surgery>transplants>");
insert into categories (category) values ("science>medicine>surgery");
insert into categories (category) values ("science>medicine>veterinary medicine");
insert into categories (category) values ("science>medicine");
insert into categories (category) values ("science>physics>atomic physics");
insert into categories (category) values ("science>physics>astrophysics");
insert into categories (category) values ("science>physics>electromagnetism");
insert into categories (category) values ("science>physics>hydraulics");
insert into categories (category) values ("science>physics>nanotechnology");
insert into categories (category) values ("science>physics>optics");
insert into categories (category) values ("science>physics>space and astronomy");
insert into categories (category) values ("science>physics>thermodynamics");
insert into categories (category) values ("science>physics");
insert into categories (category) values ("science>social science>anthropology");
insert into categories (category) values ("science>social science>history>ancient history>");
insert into categories (category) values ("science>social science>history>archaeology>");
insert into categories (category) values ("science>social science>history>genealogy>");
insert into categories (category) values ("science>social science>history>heraldry>");
insert into categories (category) values ("science>social science>history>medieval history>");
insert into categories (category) values ("science>social science>history>modern history>");
insert into categories (category) values ("science>social science>history>prehistory>");
insert into categories (category) values ("science>social science>history");
insert into categories (category) values ("science>social science>linguistics>translation>");
insert into categories (category) values ("science>social science>linguistics");
insert into categories (category) values ("science>social science>pedagogy");
insert into categories (category) values ("science>social science>philosophy>ethics>");
insert into categories (category) values ("science>social science>philosophy");
insert into categories (category) values ("science>social science>sociology");
insert into categories (category) values ("science>social science");
insert into categories (category) values ("science>weather>meteorological disaster>flood>");
insert into categories (category) values ("science>weather>meteorological disaster>hurricane>");
insert into categories (category) values ("science>weather>meteorological disaster>tornado>");
insert into categories (category) values ("science>weather>meteorological disaster");
insert into categories (category) values ("science>weather");
insert into categories (category) values ("science");
insert into categories (category) values ("shopping>auctions");
insert into categories (category) values ("shopping>classifieds");
insert into categories (category) values ("shopping>gifts>flowers");
insert into categories (category) values ("shopping>gifts>greeting cards");
insert into categories (category) values ("shopping>gifts>party supplies");
insert into categories (category) values ("shopping>gifts");
insert into categories (category) values ("shopping>resources>comparisons engines");
insert into categories (category) values ("shopping>resources>consumer protection");
insert into categories (category) values ("shopping>resources>contests and freebies");
insert into categories (category) values ("shopping>resources>coupons");
insert into categories (category) values ("shopping>resources>loyalty programs");
insert into categories (category) values ("shopping>resources>product reviews");
insert into categories (category) values ("shopping>resources>warranties and service contracts");
insert into categories (category) values ("shopping>retail>department stores");
insert into categories (category) values ("shopping>retail>online stores");
insert into categories (category) values ("shopping>retail>outlet stores");
insert into categories (category) values ("shopping>retail>second-hand market");
insert into categories (category) values ("shopping>retail>wholesalers");
insert into categories (category) values ("shopping>retail");
insert into categories (category) values ("shopping>toys>action figures");
insert into categories (category) values ("shopping>toys>dolls");
insert into categories (category) values ("shopping>toys>puppets");
insert into categories (category) values ("shopping>toys>stuffed animals");
insert into categories (category) values ("shopping>toys");
insert into categories (category) values ("shopping");
insert into categories (category) values ("society>crime>drug trafficking");
insert into categories (category) values ("society>crime>organized crime");
insert into categories (category) values ("society>crime>personal offense>assault>");
insert into categories (category) values ("society>crime>personal offense>hate crime>");
insert into categories (category) values ("society>crime>personal offense>homicide>");
insert into categories (category) values ("society>crime>personal offense>human trafficking>");
insert into categories (category) values ("society>crime>personal offense>kidnapping>");
insert into categories (category) values ("society>crime>personal offense>torture>");
insert into categories (category) values ("society>crime>property crime>arson>");
insert into categories (category) values ("society>crime>property crime>bribery>");
insert into categories (category) values ("society>crime>property crime>burglary>");
insert into categories (category) values ("society>crime>property crime>embezzlement>");
insert into categories (category) values ("society>crime>property crime>fraud>");
insert into categories (category) values ("society>crime>property crime>larceny>");
insert into categories (category) values ("society>crime>property crime>piracy>");
insert into categories (category) values ("society>crime>property crime>robbery>");
insert into categories (category) values ("society>crime>property crime>smuggling>");
insert into categories (category) values ("society>crime>property crime>usury>");
insert into categories (category) values ("society>crime>sexual offense>paedophilia>");
insert into categories (category) values ("society>crime>sexual offense>prostitution>");
insert into categories (category) values ("society>crime>sexual offense>rape>");
insert into categories (category) values ("society>crime");
insert into categories (category) values ("society>dating");
insert into categories (category) values ("society>gay life");
insert into categories (category) values ("society>racism");
insert into categories (category) values ("society>senior living");
insert into categories (category) values ("society>sex>pornography");
insert into categories (category) values ("society>sex>sex education");
insert into categories (category) values ("society>sex");
insert into categories (category) values ("society>social institution>divorce");
insert into categories (category) values ("society>social institution>marriage>common law marriage>");
insert into categories (category) values ("society>social institution>marriage>weddings>");
insert into categories (category) values ("society>social institution>marriage");
insert into categories (category) values ("society>teens");
insert into categories (category) values ("society>unrest and war");
insert into categories (category) values ("society>welfare>healthcare>hospital>");
insert into categories (category) values ("society>welfare>healthcare");
insert into categories (category) values ("society>welfare>social services>volunteering>");
insert into categories (category) values ("society>welfare>social services");
insert into categories (category) values ("society>welfare");
insert into categories (category) values ("society>work>contracts");
insert into categories (category) values ("society>work>retirement");
insert into categories (category) values ("society>work>unemployment");
insert into categories (category) values ("society>work>unions");
insert into categories (category) values ("society");
insert into categories (category) values ("sports>archery");
insert into categories (category) values ("sports>auto racing>nascar");
insert into categories (category) values ("sports>auto racing>rally");
insert into categories (category) values ("sports>auto racing");
insert into categories (category) values ("sports>badminton");
insert into categories (category) values ("sports>baseball");
insert into categories (category) values ("sports>basketball");
insert into categories (category) values ("sports>bicycling>mountain biking");
insert into categories (category) values ("sports>bicycling");
insert into categories (category) values ("sports>billiards");
insert into categories (category) values ("sports>boat racing");
insert into categories (category) values ("sports>bobsled");
insert into categories (category) values ("sports>bodybuilding");
insert into categories (category) values ("sports>bowling");
insert into categories (category) values ("sports>boxing");
insert into categories (category) values ("sports>canoeing and kayaking");
insert into categories (category) values ("sports>cheerleading");
insert into categories (category) values ("sports>climbing>mountain climbing");
insert into categories (category) values ("sports>climbing>rock climbing");
insert into categories (category) values ("sports>climbing");
insert into categories (category) values ("sports>cricket");
insert into categories (category) values ("sports>curling");
insert into categories (category) values ("sports>diving");
insert into categories (category) values ("sports>dog sled");
insert into categories (category) values ("sports>fencing");
insert into categories (category) values ("sports>fishing>fly fishing");
insert into categories (category) values ("sports>fishing>freshwater fishing");
insert into categories (category) values ("sports>fishing>saltwater fishing");
insert into categories (category) values ("sports>fishing>sport fishing");
insert into categories (category) values ("sports>fishing");
insert into categories (category) values ("sports>football");
insert into categories (category) values ("sports>go kart");
insert into categories (category) values ("sports>golf");
insert into categories (category) values ("sports>gymnastics>calisthenics");
insert into categories (category) values ("sports>gymnastics");
insert into categories (category) values ("sports>handball");
insert into categories (category) values ("sports>hockey>field hockey");
insert into categories (category) values ("sports>hockey");
insert into categories (category) values ("sports>horse racing");
insert into categories (category) values ("sports>horses");
insert into categories (category) values ("sports>hunting and shooting>skeet shooting");
insert into categories (category) values ("sports>hunting and shooting>target shooting");
insert into categories (category) values ("sports>hunting and shooting");
insert into categories (category) values ("sports>martial arts>judo");
insert into categories (category) values ("sports>martial arts>karate");
insert into categories (category) values ("sports>martial arts>sumo");
insert into categories (category) values ("sports>martial arts");
insert into categories (category) values ("sports>motorcycling");
insert into categories (category) values ("sports>olympics>paralympic games");
insert into categories (category) values ("sports>olympics");
insert into categories (category) values ("sports>paintball");
insert into categories (category) values ("sports>parachuting");
insert into categories (category) values ("sports>polo");
insert into categories (category) values ("sports>rodeo");
insert into categories (category) values ("sports>rowing");
insert into categories (category) values ("sports>rugby");
insert into categories (category) values ("sports>running and jogging");
insert into categories (category) values ("sports>sailing");
insert into categories (category) values ("sports>scuba diving");
insert into categories (category) values ("sports>skateboarding");
insert into categories (category) values ("sports>skating>figure skating");
insert into categories (category) values ("sports>skating>ice skating");
insert into categories (category) values ("sports>skating>roller skating");
insert into categories (category) values ("sports>skating");
insert into categories (category) values ("sports>skiing>downhill skiing");
insert into categories (category) values ("sports>skiing>nordic skiing");
insert into categories (category) values ("sports>skiing>waterskiing");
insert into categories (category) values ("sports>skiing");
insert into categories (category) values ("sports>snowboarding");
insert into categories (category) values ("sports>soccer");
insert into categories (category) values ("sports>softball");
insert into categories (category) values ("sports>sports news");
insert into categories (category) values ("sports>surfing and bodyboarding");
insert into categories (category) values ("sports>swimming");
insert into categories (category) values ("sports>table tennis and ping-pong");
insert into categories (category) values ("sports>tennis");
insert into categories (category) values ("sports>trekking");
insert into categories (category) values ("sports>volleyball>beach volleyball");
insert into categories (category) values ("sports>volleyball");
insert into categories (category) values ("sports>wakeboarding");
insert into categories (category) values ("sports>walking");
insert into categories (category) values ("sports>water polo");
insert into categories (category) values ("sports>weightlifting");
insert into categories (category) values ("sports>windsurfing");
insert into categories (category) values ("sports>wrestling");
insert into categories (category) values ("sports");
insert into categories (category) values ("style and fashion>accessories>backpacks");
insert into categories (category) values ("style and fashion>accessories>gloves");
insert into categories (category) values ("style and fashion>accessories>hats");
insert into categories (category) values ("style and fashion>accessories>scarves");
insert into categories (category) values ("style and fashion>accessories>socks");
insert into categories (category) values ("style and fashion>accessories>sunglasses");
insert into categories (category) values ("style and fashion>accessories>ties");
insert into categories (category) values ("style and fashion>accessories>wallets");
insert into categories (category) values ("style and fashion>accessories>watches");
insert into categories (category) values ("style and fashion>accessories");
insert into categories (category) values ("style and fashion>beauty>cologne");
insert into categories (category) values ("style and fashion>beauty>cosmetics>eyeshadow>");
insert into categories (category) values ("style and fashion>beauty>cosmetics>lipstick>");
insert into categories (category) values ("style and fashion>beauty>cosmetics>nail polish>");
insert into categories (category) values ("style and fashion>beauty>cosmetics");
insert into categories (category) values ("style and fashion>beauty>cosmetology and beauty professionals");
insert into categories (category) values ("style and fashion>beauty>face and body care>body care>");
insert into categories (category) values ("style and fashion>beauty>face and body care>hygiene and toiletries>");
insert into categories (category) values ("style and fashion>beauty>face and body care>nail care>");
insert into categories (category) values ("style and fashion>beauty>hair care");
insert into categories (category) values ("style and fashion>beauty>perfume");
insert into categories (category) values ("style and fashion>beauty>tattoos");
insert into categories (category) values ("style and fashion>body art");
insert into categories (category) values ("style and fashion>clothing>blazers");
insert into categories (category) values ("style and fashion>clothing>coats");
insert into categories (category) values ("style and fashion>clothing>hoodies");
insert into categories (category) values ("style and fashion>clothing>jackets");
insert into categories (category) values ("style and fashion>clothing>leggings");
insert into categories (category) values ("style and fashion>clothing>lingerie");
insert into categories (category) values ("style and fashion>clothing>pajamas");
insert into categories (category) values ("style and fashion>clothing>pants>jeans>");
insert into categories (category) values ("style and fashion>clothing>pants");
insert into categories (category) values ("style and fashion>clothing>petticoats");
insert into categories (category) values ("style and fashion>clothing>shirts");
insert into categories (category) values ("style and fashion>clothing>shorts");
insert into categories (category) values ("style and fashion>clothing>skirts");
insert into categories (category) values ("style and fashion>clothing>sweaters");
insert into categories (category) values ("style and fashion>clothing>wedding dresses");
insert into categories (category) values ("style and fashion>clothing");
insert into categories (category) values ("style and fashion>fashion designers");
insert into categories (category) values ("style and fashion>footwear>boots");
insert into categories (category) values ("style and fashion>footwear>sandals");
insert into categories (category) values ("style and fashion>footwear>shoes");
insert into categories (category) values ("style and fashion>footwear>slippers");
insert into categories (category) values ("style and fashion>footwear>sneakers");
insert into categories (category) values ("style and fashion>footwear");
insert into categories (category) values ("style and fashion>jewelry>bracelets");
insert into categories (category) values ("style and fashion>jewelry>earrings");
insert into categories (category) values ("style and fashion>jewelry>necklaces");
insert into categories (category) values ("style and fashion>jewelry>rings");
insert into categories (category) values ("style and fashion>jewelry");
insert into categories (category) values ("style and fashion>luxury goods");
insert into categories (category) values ("style and fashion>men 's fashion");
insert into categories (category) values ("style and fashion>swimwear>bikinis");
insert into categories (category) values ("style and fashion>swimwear");
insert into categories (category) values ("style and fashion>underwear");
insert into categories (category) values ("style and fashion");
insert into categories (category) values ("technology and computing>computer certification");
insert into categories (category) values ("technology and computing>computer crime");
insert into categories (category) values ("technology and computing>computer reviews");
insert into categories (category) values ("technology and computing>computer security>antivirus and malware");
insert into categories (category) values ("technology and computing>computer security>network security");
insert into categories (category) values ("technology and computing>computer security");
insert into categories (category) values ("technology and computing>consumer electronics>audio equipment>headphones>");
insert into categories (category) values ("technology and computing>consumer electronics>audio equipment>speakers>");
insert into categories (category) values ("technology and computing>consumer electronics>audio equipment>stereo systems and components>");
insert into categories (category) values ("technology and computing>consumer electronics>audio equipment");
insert into categories (category) values ("technology and computing>consumer electronics>camera and photo equipment>binoculars>");
insert into categories (category) values ("technology and computing>consumer electronics>camera and photo equipment>cameras and camcorders>camcorders");
insert into categories (category) values ("technology and computing>consumer electronics>camera and photo equipment>cameras and camcorders>camera bags");
insert into categories (category) values ("technology and computing>consumer electronics>camera and photo equipment>cameras and camcorders>camera batteries");
insert into categories (category) values ("technology and computing>consumer electronics>camera and photo equipment>cameras and camcorders>camera lenses");
insert into categories (category) values ("technology and computing>consumer electronics>camera and photo equipment>cameras and camcorders>cameras");
insert into categories (category) values ("technology and computing>consumer electronics>camera and photo equipment>telescopes>");
insert into categories (category) values ("technology and computing>consumer electronics>ebook reader");
insert into categories (category) values ("technology and computing>consumer electronics>game systems and consoles>nintendo>");
insert into categories (category) values ("technology and computing>consumer electronics>game systems and consoles>playstation>");
insert into categories (category) values ("technology and computing>consumer electronics>game systems and consoles>xbox>");
insert into categories (category) values ("technology and computing>consumer electronics>game systems and consoles");
insert into categories (category) values ("technology and computing>consumer electronics>home video and dvd");
insert into categories (category) values ("technology and computing>consumer electronics>portable entertainment");
insert into categories (category) values ("technology and computing>consumer electronics>radios");
insert into categories (category) values ("technology and computing>consumer electronics>telephones>mobile phones>smart phones");
insert into categories (category) values ("technology and computing>consumer electronics>telephones>mobile phones>");
insert into categories (category) values ("technology and computing>consumer electronics>telephones");
insert into categories (category) values ("technology and computing>consumer electronics>tv and video equipment>dvrs and set-top boxes>");
insert into categories (category) values ("technology and computing>consumer electronics>tv and video equipment>home theater systems>");
insert into categories (category) values ("technology and computing>consumer electronics>tv and video equipment>projectors>");
insert into categories (category) values ("technology and computing>consumer electronics>tv and video equipment>televisions>hdtvs");
insert into categories (category) values ("technology and computing>consumer electronics>tv and video equipment>televisions>lcd tvs");
insert into categories (category) values ("technology and computing>consumer electronics>tv and video equipment>televisions>plasma tvs");
insert into categories (category) values ("technology and computing>consumer electronics>tv and video equipment>televisions>");
insert into categories (category) values ("technology and computing>consumer electronics>tv and video equipment>video players and recorders>blu-ray players and recorders");
insert into categories (category) values ("technology and computing>consumer electronics>tv and video equipment>video players and recorders>dvd players and recorders");
insert into categories (category) values ("technology and computing>consumer electronics>tv and video equipment");
insert into categories (category) values ("technology and computing>consumer electronics");
insert into categories (category) values ("technology and computing>data centers");
insert into categories (category) values ("technology and computing>electronic components");
insert into categories (category) values ("technology and computing>enterprise technology>customer relationship management");
insert into categories (category) values ("technology and computing>enterprise technology>data management");
insert into categories (category) values ("technology and computing>enterprise technology>enterprise resource planning");
insert into categories (category) values ("technology and computing>hardware>computer>desktop computer>");
insert into categories (category) values ("technology and computing>hardware>computer>portable computer>laptop");
insert into categories (category) values ("technology and computing>hardware>computer>portable computer>palmtops and pdas");
insert into categories (category) values ("technology and computing>hardware>computer>portable computer>tablet");
insert into categories (category) values ("technology and computing>hardware>computer>portable computer>");
insert into categories (category) values ("technology and computing>hardware>computer>servers>");
insert into categories (category) values ("technology and computing>hardware>computer");
insert into categories (category) values ("technology and computing>hardware>computer components>chips and processors>");
insert into categories (category) values ("technology and computing>hardware>computer components>disks>");
insert into categories (category) values ("technology and computing>hardware>computer components>graphics cards>");
insert into categories (category) values ("technology and computing>hardware>computer components>memory>portable");
insert into categories (category) values ("technology and computing>hardware>computer components>memory>");
insert into categories (category) values ("technology and computing>hardware>computer components>motherboards>");
insert into categories (category) values ("technology and computing>hardware>computer components>sound cards>");
insert into categories (category) values ("technology and computing>hardware>computer networking>router>");
insert into categories (category) values ("technology and computing>hardware>computer networking>wireless technology>");
insert into categories (category) values ("technology and computing>hardware>computer peripherals>computer monitors>");
insert into categories (category) values ("technology and computing>hardware>computer peripherals>printers, copiers and fax>copiers");
insert into categories (category) values ("technology and computing>hardware>computer peripherals>printers, copiers and fax>fax machines");
insert into categories (category) values ("technology and computing>hardware>computer peripherals>printers, copiers and fax>printers");
insert into categories (category) values ("technology and computing>hardware>computer peripherals>printers, copiers and fax>scanners");
insert into categories (category) values ("technology and computing>hardware>computer peripherals");
insert into categories (category) values ("technology and computing>hardware");
insert into categories (category) values ("technology and computing>internet technology>chat");
insert into categories (category) values ("technology and computing>internet technology>ecommerce");
insert into categories (category) values ("technology and computing>internet technology>email");
insert into categories (category) values ("technology and computing>internet technology>internet cafes");
insert into categories (category) values ("technology and computing>internet technology>isps");
insert into categories (category) values ("technology and computing>internet technology>social network");
insert into categories (category) values ("technology and computing>internet technology>web clip art");
insert into categories (category) values ("technology and computing>internet technology>web design and html");
insert into categories (category) values ("technology and computing>internet technology>web search>people search>");
insert into categories (category) values ("technology and computing>internet technology>web search");
insert into categories (category) values ("technology and computing>internet technology");
insert into categories (category) values ("technology and computing>mp3 and midi");
insert into categories (category) values ("technology and computing>networking>network monitoring and management");
insert into categories (category) values ("technology and computing>networking>vpn and remote access");
insert into categories (category) values ("technology and computing>networking");
insert into categories (category) values ("technology and computing>operating systems>linux");
insert into categories (category) values ("technology and computing>operating systems>mac os");
insert into categories (category) values ("technology and computing>operating systems>unix");
insert into categories (category) values ("technology and computing>operating systems>windows");
insert into categories (category) values ("technology and computing>operating systems");
insert into categories (category) values ("technology and computing>programming languages>c and c++");
insert into categories (category) values ("technology and computing>programming languages>java");
insert into categories (category) values ("technology and computing>programming languages>javascript");
insert into categories (category) values ("technology and computing>programming languages>visual basic");
insert into categories (category) values ("technology and computing>programming languages");
insert into categories (category) values ("technology and computing>software>databases");
insert into categories (category) values ("technology and computing>software>desktop publishing");
insert into categories (category) values ("technology and computing>software>desktop video");
insert into categories (category) values ("technology and computing>software>graphics software>animation>");
insert into categories (category) values ("technology and computing>software>graphics software");
insert into categories (category) values ("technology and computing>software>net conferencing");
insert into categories (category) values ("technology and computing>software>shareware and freeware");
insert into categories (category) values ("technology and computing>software");
insert into categories (category) values ("technology and computing>tech news");
insert into categories (category) values ("technology and computing>technical support");
insert into categories (category) values ("technology and computing>technological innovation");
insert into categories (category) values ("technology and computing");
insert into categories (category) values ("travel>budget travel");
insert into categories (category) values ("travel>business travel");
insert into categories (category) values ("travel>honeymoons and getaways");
insert into categories (category) values ("travel>hotels");
insert into categories (category) values ("travel>specialty travel>adventure travel");
insert into categories (category) values ("travel>specialty travel>ecotourism");
insert into categories (category) values ("travel>specialty travel>sightseeing tours");
insert into categories (category) values ("travel>specialty travel>vineyards");
insert into categories (category) values ("travel>tourist destinations>africa");
insert into categories (category) values ("travel>tourist destinations>australia and new zealand");
insert into categories (category) values ("travel>tourist destinations>canada");
insert into categories (category) values ("travel>tourist destinations>caribbean");
insert into categories (category) values ("travel>tourist destinations>eastern europe");
insert into categories (category) values ("travel>tourist destinations>europe");
insert into categories (category) values ("travel>tourist destinations>france");
insert into categories (category) values ("travel>tourist destinations>greece");
insert into categories (category) values ("travel>tourist destinations>italy");
insert into categories (category) values ("travel>tourist destinations>japan");
insert into categories (category) values ("travel>tourist destinations>mexico and central america");
insert into categories (category) values ("travel>tourist destinations>national parks");
insert into categories (category) values ("travel>tourist destinations>seaside resort");
insert into categories (category) values ("travel>tourist destinations>ski resorts");
insert into categories (category) values ("travel>tourist destinations>south america");
insert into categories (category) values ("travel>tourist destinations>spas");
insert into categories (category) values ("travel>tourist destinations>theme parks");
insert into categories (category) values ("travel>tourist destinations>united kingdom");
insert into categories (category) values ("travel>tourist destinations");
insert into categories (category) values ("travel>tourist facilities>bed and breakfast");
insert into categories (category) values ("travel>tourist facilities>camping");
insert into categories (category) values ("travel>tourist facilities>hotel");
insert into categories (category) values ("travel>transports>air travel>air and space accident>");
insert into categories (category) values ("travel>transports>air travel>airfare>");
insert into categories (category) values ("travel>transports>air travel>airlines>");
insert into categories (category) values ("travel>transports>air travel>airplanes>");
insert into categories (category) values ("travel>transports>air travel>airports>");
insert into categories (category) values ("travel>transports>air travel>helicopters>");
insert into categories (category) values ("travel>transports>air travel");
insert into categories (category) values ("travel>transports>public transport");
insert into categories (category) values ("travel>transports>road travel>road accident>");
insert into categories (category) values ("travel>transports>sea travel>cruises>");
insert into categories (category) values ("travel>transports>train travel");
insert into categories (category) values ("travel>travel agencies");
insert into categories (category) values ("travel>travel guides");
insert into categories (category) values ("travel>traveling with kids");
insert into categories (category) values ("travel>vacation rentals");
insert into categories (category) values ("travel");


